/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmangamentgui;
import javax.swing.JOptionPane;
import Connector.ConnectionProvider;
import java.sql.*;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author cy759
 */
public class AddDiagnosis extends javax.swing.JFrame {

    /**
     * Creates new form AddDiagnosis
     */
    public AddDiagnosis() {
        initComponents();
        jLabelmessage.setVisible(false);
          jLabeltype.setVisible(false);
            jComboBox1.setVisible(false);
    }
    int flag=0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldpatient = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelmessage = new javax.swing.JLabel();
        jLabelSysmptoms = new javax.swing.JLabel();
        jLabelDiagnosis = new javax.swing.JLabel();
        jLabelMedicines = new javax.swing.JLabel();
        jLabelward = new javax.swing.JLabel();
        jTextFieldsymptoms = new javax.swing.JTextField();
        jTextFieldDiagnosis = new javax.swing.JTextField();
        jTextfieldmedicines = new javax.swing.JTextField();
        jButtonsubmit = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabeltype = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("PatientId");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 31, 81, 25));

        jTextFieldpatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldpatientActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldpatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 34, 92, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmangamentgui/icons8-search-30.png"))); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 24, 145, -1));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PatientId", "Name", "Age", "Contact", "Gender", "BloodGroup", "Address"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 113, 721, 91));

        jLabelmessage.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelmessage.setForeground(new java.awt.Color(255, 51, 0));
        jLabelmessage.setText("PatientId does not exist");
        getContentPane().add(jLabelmessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 69, -1, 26));

        jLabelSysmptoms.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSysmptoms.setText("Sysmptoms");
        getContentPane().add(jLabelSysmptoms, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 237, 77, 23));

        jLabelDiagnosis.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelDiagnosis.setText("Diagnosis");
        getContentPane().add(jLabelDiagnosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 298, 77, 25));

        jLabelMedicines.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelMedicines.setText("Medicines");
        getContentPane().add(jLabelMedicines, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 367, 68, 28));

        jLabelward.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelward.setText("Ward Required ");
        getContentPane().add(jLabelward, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 237, -1, 23));
        getContentPane().add(jTextFieldsymptoms, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 239, 61, -1));
        getContentPane().add(jTextFieldDiagnosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 301, 61, -1));
        getContentPane().add(jTextfieldmedicines, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 372, 61, -1));

        jButtonsubmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonsubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmangamentgui/icons8-submit-document-32.png"))); // NOI18N
        jButtonsubmit.setText("Submit");
        jButtonsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsubmitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 459, 134, 38));

        jButtonCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmangamentgui/icons8-close-30.png"))); // NOI18N
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 459, -1, -1));

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(642, 237, -1, -1));

        jLabeltype.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabeltype.setText("Type");
        getContentPane().add(jLabeltype, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 37, 25));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Good", "vip", "great" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, 72, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmangamentgui/bed.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          String patientID = jTextFieldpatient.getText();
        try{
            Connection con = ConnectionProvider.getcon();
            Statement st = con.prepareStatement("create", ResultSet.TYPE_SCROLL_SENSITIVE, 
                        ResultSet.CONCUR_UPDATABLE);
            ResultSet rs = st.executeQuery("select * from patient where PatientID='"+patientID+"'");
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            if(!rs.first()){             
                jLabelmessage.setVisible(true);
            }
            else{
                jLabelmessage.setVisible(false);
                jTextFieldpatient.setEditable(false);
                    flag=1;
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected())
        {
            jLabeltype.setVisible(true);
            jComboBox1.setVisible(true);
        }
        else{
              jLabeltype.setVisible(false);
            jComboBox1.setVisible(false);
        
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        int flag=JOptionPane.showConfirmDialog(null, "Are you sure want to exit", "submit",JOptionPane.YES_NO_OPTION);
      if(flag==0){
         setVisible(false);
         new Home().setVisible(true);
      }
          
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsubmitActionPerformed
        // TODO add your handling code here:
          if(flag==1)
        {
            String patientId=jTextFieldpatient.getText();
            String symptoms=jTextFieldsymptoms.getText();
           String diagnosis=jTextFieldDiagnosis.getText();
            String medicines=jTextfieldmedicines.getText();

         String wardReq;
            String typeWard;
            if(jCheckBox1.isSelected()){
                wardReq = "Yes";
                typeWard = (String)jComboBox1.getSelectedItem();
        }
              else{
                wardReq = "No";
                typeWard = "";
            }
           try{
            Connection con = ConnectionProvider.getcon();
            Statement st = con.createStatement();
            st.executeUpdate("insert into diagnosis values('"+ patientId + "', '" + symptoms +"', '"+ diagnosis +"', '"+ medicines +"', '"+ wardReq +"', '"+ typeWard + "')");
            JOptionPane.showMessageDialog(null, "Successfully Added");
                setVisible(false);
               new AddDiagnosis().setVisible(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }                                             

    }//GEN-LAST:event_jButtonsubmitActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextFieldpatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldpatientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldpatientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDiagnosis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDiagnosis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDiagnosis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDiagnosis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDiagnosis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonsubmit;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelDiagnosis;
    private javax.swing.JLabel jLabelMedicines;
    private javax.swing.JLabel jLabelSysmptoms;
    private javax.swing.JLabel jLabelmessage;
    private javax.swing.JLabel jLabeltype;
    private javax.swing.JLabel jLabelward;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldDiagnosis;
    private javax.swing.JTextField jTextFieldpatient;
    private javax.swing.JTextField jTextFieldsymptoms;
    private javax.swing.JTextField jTextfieldmedicines;
    // End of variables declaration//GEN-END:variables
}
