/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmangamentgui;

import javax.swing.JOptionPane;

/**
 *
 * @author cy759
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        addpatientbutton = new javax.swing.JButton();
        AdddiagnosisButton = new javax.swing.JButton();
        patienthistoryButton = new javax.swing.JButton();
        updatepatientButton = new javax.swing.JButton();
        hsInfoButton = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmangamentgui/bed.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addpatientbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addpatientbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmangamentgui/icons8-patient-50.png"))); // NOI18N
        addpatientbutton.setText("Add New Patient");
        addpatientbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpatientbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(addpatientbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        AdddiagnosisButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AdddiagnosisButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmangamentgui/icons8-patient-64.png"))); // NOI18N
        AdddiagnosisButton.setText("Add Diagnosis Info");
        AdddiagnosisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdddiagnosisButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AdddiagnosisButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 210, 60));

        patienthistoryButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        patienthistoryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmangamentgui/icons8-scroll-32.png"))); // NOI18N
        patienthistoryButton.setText("Full Patient History");
        patienthistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patienthistoryButtonActionPerformed(evt);
            }
        });
        getContentPane().add(patienthistoryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 207, 60));

        updatepatientButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updatepatientButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmangamentgui/icons8-checklist-30.png"))); // NOI18N
        updatepatientButton.setText("Update Patient Resource");
        updatepatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatepatientButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updatepatientButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 207, 60));

        hsInfoButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hsInfoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmangamentgui/icons8-information-24.png"))); // NOI18N
        hsInfoButton.setText("Hospital Infromation");
        hsInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hsInfoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(hsInfoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 207, 50));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmangamentgui/icons8-logout-50.png"))); // NOI18N
        jButton7.setText("Logout");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 160, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmangamentgui/bed.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addpatientbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpatientbuttonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new AddNewPatient().setVisible(true);
       
    }//GEN-LAST:event_addpatientbuttonActionPerformed

    private void AdddiagnosisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdddiagnosisButtonActionPerformed
        // TODO add your handling code here:
          new AddDiagnosis().setVisible(true);
    }//GEN-LAST:event_AdddiagnosisButtonActionPerformed

    private void patienthistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patienthistoryButtonActionPerformed
        // TODO add your handling code here:
          new FullPatientHistory().setVisible(true);
    }//GEN-LAST:event_patienthistoryButtonActionPerformed

    private void updatepatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatepatientButtonActionPerformed
        // TODO add your handling code here:
          new Updatepatient().setVisible(true);
    }//GEN-LAST:event_updatepatientButtonActionPerformed

    private void hsInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hsInfoButtonActionPerformed
        // TODO add your handling code here:
          new HospitalInformation().setVisible(true);
    }//GEN-LAST:event_hsInfoButtonActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int flag=JOptionPane.showConfirmDialog(null, "Are you sure want to Logout","Submit",JOptionPane.OK_CANCEL_OPTION);
        if(flag==0)
        {
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdddiagnosisButton;
    private javax.swing.JButton addpatientbutton;
    private javax.swing.JButton hsInfoButton;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton patienthistoryButton;
    private javax.swing.JButton updatepatientButton;
    // End of variables declaration//GEN-END:variables
}
